:rooms:
  :cuisine:
    :name: 'Cuisine'
    :color: '#34129F'
  :bas:
    :name: 'Salle du bas'
    :color: '#FFD300'
  :haut:
    :name: 'Salle du haut'
    :color: '#FE0008'
:calendar:
  :server: './public/'
  :reservations: 'reservation.ics'
  :test: 'tests.ics'
  :name: 'export.ics'
