---
  environment: development
  chdir: .
  address: 127.0.0.1
  port: 3000
  pid: tmp/thin.pid
  rackup: config/resa.ru
  log: log/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: false
